#!/bin/bash

if [ -z "$WATER" ] || [ -z "$STIR" ]; then
  echo "Both WATER and STIR environment variables must be set."
else
  water_to_base10() {
    local result=0
    local multiplier=1
    local str="$1"

    for ((i = ${#str} - 1; i >= 0; i--)); do
      local char="${str:i:1}"
      case "$char" in
        e) digit=0 ;;
        w) digit=1 ;;
        a) digit=2 ;;
        t) digit=3 ;;
        r) digit=4 ;;
        *) continue ;;
      esac
      result=$((result + digit * multiplier))
      multiplier=$((multiplier * 5))
    done

    echo "$result"
  }

  stir_to_base10() {
    local result=0
    local multiplier=1
    local str="$1"

    for ((i = ${#str} - 1; i >= 0; i--)); do
      local char="${str:i:1}"
      case "$char" in
        t) digit=0 ;;
        i) digit=1 ;;
        r) digit=2 ;;
        s) digit=3 ;;
        .) digit=4 ;;
        *) continue ;;
      esac
      result=$((result + digit * multiplier))
      multiplier=$((multiplier * 5))
    done

    echo "$result"
  }

  water_base10=$(water_to_base10 "$WATER")
  stir_base10=$(stir_to_base10 "$STIR")

  result_base10=$((water_base10 + stir_base10))

  base10_to_bestchol() {
    local num="$1"
    local charset="bestchol"
    local base=${#charset}

    local result=""
    while [ "$num" -gt 0 ]; do
      local remainder=$((num % base))
      local digit="${charset:remainder:1}"
      result="${digit}${result}"
      num=$((num / base))
    done

    echo "$result"
  }

  result_bestchol=$(base10_to_bestchol "$result_base10")

  echo "$result_bestchol"
fi

