#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Get the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Terminated"
else
    echo "No running instance of 4-to_infinity_and_beyond found."
fi

