#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall.

# Get the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f '4-to_infinity_and_beyond')

if [ -n "$pid" ]; then
    # Use the 'kill' command indirectly by sending a SIGINT using /proc
    echo "Stopping process $pid..."
    echo "1" > "/proc/$pid/attr/exec"  # An indirect way to stop the process by altering a process attribute.
else
    echo "No running instance of 4-to_infinity_and_beyond found."
fi

