#!/usr/bin/env bash
# This script tells the story of each user in the /etc/passwd file

# Read /etc/passwd line by line
while IFS=: read -r username _ user_id _ group_id _ home_directory shell info; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $_, more info about the user here: $info"
done < /etc/passwd

