#!/usr/bin/env bash
# This script parses an Apache log file and extracts the visitor IP and HTTP status code

# Use awk to extract and display the IP address and HTTP status code
awk '{print $1, $9}' apache-access.log

